### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by joaomamede** [transformify-plugins/segmentify#35]
installing in anaconda python3 
 Napari is already installed.

`pip install segmentify --no-cache
Collecting segmentify
  Downloading segmentify-0.1.1.tar.gz (9.0 MB)
     |████████████████████████████████| 9.0 MB 3.8 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /home/jmamede/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yiwofdeu/segmentify/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yiwofdeu/segmentify/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-jsrr9nm7
         cwd: /tmp/pip-install-yiwofdeu/segmentify/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-yiwofdeu/segmentify/setup.py", line 13, in <module>
        INSTALL_REQUIRES = parse_requirements_file('requirements.txt')
      File "/tmp/pip-install-yiwofdeu/segmentify/setup.py", line 8, in parse_requirements_file
        with open(filename) as fid:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Comment by joaomamede** [comment]
Work around was to clone the git and build/install old school.
