### ISSUE TITLE
Error when segmenting

### ISSUE THREAD

**Issue by joaomamede** [transformify-plugins/segmentify#36]
Hi, first use resulted in errors.
Can anyone point me to a fix?

```
Segmenting...
ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/home/jmamede/anaconda3/lib/python3.8/site-packages/magicgui/core.py", line 199, in <lambda>
    self.call_button.clicked.connect(lambda checked: self.__call__())
  File "/home/jmamede/anaconda3/lib/python3.8/site-packages/magicgui/core.py", line 532, in __call__
    value = self.func(**_kwargs)
  File "/home/jmamede/anaconda3/lib/python3.8/site-packages/segmentify-0.1.1-py3.8.egg/segmentify/gui.py", line 29, in segmentation
    clf, features = fit(data, initial_labels.data, featurizer=featurizer.value)
  File "/home/jmamede/anaconda3/lib/python3.8/site-packages/segmentify-0.1.1-py3.8.egg/segmentify/semantic/main.py", line 129, in fit
    padded_features = unet_featurize(padded_image, featurizer)
  File "/home/jmamede/anaconda3/lib/python3.8/site-packages/segmentify-0.1.1-py3.8.egg/segmentify/semantic/main.py", line 59, in unet_featurize
    features = model(image)
  File "/home/jmamede/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jmamede/anaconda3/lib/python3.8/site-packages/segmentify-0.1.1-py3.8.egg/segmentify/model/unet.py", line 57, in forward
    x = self.decode_4(x, skip_4)
  File "/home/jmamede/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jmamede/anaconda3/lib/python3.8/site-packages/segmentify-0.1.1-py3.8.egg/segmentify/model/layers/unet_layers.py", line 63, in forward
    output += skip
RuntimeError: The size of tensor a (254) must match the size of tensor b (255) at non-singleton dimension 2

```

These were the labels I made before:
![image](https://user-images.githubusercontent.com/46799914/93009915-faf60180-f54b-11ea-9e81-0a2ed5f812fe.png)

Same error example:
![image](https://user-images.githubusercontent.com/46799914/93165045-a041de80-f6e0-11ea-891d-046d17e4c032.png)

I started things with:

```
    import napari 
    from segmentify import segmentation 

    with napari.gui_qt(): 
        viewer = napari.Viewer() 
    
        # instantiate the segmentify widget 
        gui = segmentation.Gui() 

        # add the new widget to the napari viewer 
        viewer.window.add_dock_widget(gui) 
 
        # keep the dropdown menus in the gui in sync with the layer model 
        viewer.layers.events.changed.connect(lambda x: gui.refresh_choices() )
```
                                                                    `

**Comment by joaomamede** [comment]
Okay. 
Original image was 2044x2048. It resulted in that error
I clipped the 4 pixels to ahve a 2044x2044 and the segmentation worked.

**Comment by sofroniewn** [comment]
Hi @joaomamede, sorry I'm just seeing this now, yes - the original model might only have worked on square images, see https://github.com/transformify-plugins/segmentify/issues/34#issue-646327777. I'm not sure how easy that would be to fix, but if you were interested in working on a PR I'd happily review! I can look into it a bit too, but it's been a while since i've looked at this repo

**Comment by sofroniewn** [comment]
@joaomamede I suspect this may have now been fixed by #37, but let me know if you're still seeing issues.
